/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as TamLinhRouteImport } from './routes/tam-linh'
import { Route as PhongThuyRouteImport } from './routes/phong-thuy'
import { Route as NghienCuuRouteImport } from './routes/nghien-cuu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PostsSlugRouteImport } from './routes/posts.$slug'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminPostsNewRouteImport } from './routes/admin/posts.new'
import { Route as AdminPostsIdEditRouteImport } from './routes/admin/posts.$id.edit'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TamLinhRoute = TamLinhRouteImport.update({
  id: '/tam-linh',
  path: '/tam-linh',
  getParentRoute: () => rootRouteImport,
} as any)
const PhongThuyRoute = PhongThuyRouteImport.update({
  id: '/phong-thuy',
  path: '/phong-thuy',
  getParentRoute: () => rootRouteImport,
} as any)
const NghienCuuRoute = NghienCuuRouteImport.update({
  id: '/nghien-cuu',
  path: '/nghien-cuu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/admin/posts/new',
  path: '/admin/posts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsIdEditRoute = AdminPostsIdEditRouteImport.update({
  id: '/admin/posts/$id/edit',
  path: '/admin/posts/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/nghien-cuu': typeof NghienCuuRoute
  '/phong-thuy': typeof PhongThuyRoute
  '/tam-linh': typeof TamLinhRoute
  '/videos': typeof VideosRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/media': typeof AdminMediaRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/nghien-cuu': typeof NghienCuuRoute
  '/phong-thuy': typeof PhongThuyRoute
  '/tam-linh': typeof TamLinhRoute
  '/videos': typeof VideosRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/media': typeof AdminMediaRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/posts': typeof PostsIndexRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/nghien-cuu': typeof NghienCuuRoute
  '/phong-thuy': typeof PhongThuyRoute
  '/tam-linh': typeof TamLinhRoute
  '/videos': typeof VideosRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/media': typeof AdminMediaRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/nghien-cuu'
    | '/phong-thuy'
    | '/tam-linh'
    | '/videos'
    | '/admin/categories'
    | '/admin/media'
    | '/posts/$slug'
    | '/admin/'
    | '/posts/'
    | '/admin/posts/new'
    | '/admin/posts/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/nghien-cuu'
    | '/phong-thuy'
    | '/tam-linh'
    | '/videos'
    | '/admin/categories'
    | '/admin/media'
    | '/posts/$slug'
    | '/admin'
    | '/posts'
    | '/admin/posts/new'
    | '/admin/posts/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/nghien-cuu'
    | '/phong-thuy'
    | '/tam-linh'
    | '/videos'
    | '/admin/categories'
    | '/admin/media'
    | '/posts/$slug'
    | '/admin/'
    | '/posts/'
    | '/admin/posts/new'
    | '/admin/posts/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  NghienCuuRoute: typeof NghienCuuRoute
  PhongThuyRoute: typeof PhongThuyRoute
  TamLinhRoute: typeof TamLinhRoute
  VideosRoute: typeof VideosRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminMediaRoute: typeof AdminMediaRoute
  PostsSlugRoute: typeof PostsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
  AdminPostsNewRoute: typeof AdminPostsNewRoute
  AdminPostsIdEditRoute: typeof AdminPostsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tam-linh': {
      id: '/tam-linh'
      path: '/tam-linh'
      fullPath: '/tam-linh'
      preLoaderRoute: typeof TamLinhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phong-thuy': {
      id: '/phong-thuy'
      path: '/phong-thuy'
      fullPath: '/phong-thuy'
      preLoaderRoute: typeof PhongThuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nghien-cuu': {
      id: '/nghien-cuu'
      path: '/nghien-cuu'
      fullPath: '/nghien-cuu'
      preLoaderRoute: typeof NghienCuuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/admin/posts/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/$id/edit': {
      id: '/admin/posts/$id/edit'
      path: '/admin/posts/$id/edit'
      fullPath: '/admin/posts/$id/edit'
      preLoaderRoute: typeof AdminPostsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  NghienCuuRoute: NghienCuuRoute,
  PhongThuyRoute: PhongThuyRoute,
  TamLinhRoute: TamLinhRoute,
  VideosRoute: VideosRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminMediaRoute: AdminMediaRoute,
  PostsSlugRoute: PostsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
  AdminPostsNewRoute: AdminPostsNewRoute,
  AdminPostsIdEditRoute: AdminPostsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
